### ISSUE TITLE
zsh-quickstart-kit should either warn fzf not installed or not install fzf-zsh-plugin

### ISSUE THREAD

**Issue by retnuh** [unixorn/zsh-quickstart-kit#122]
I upgraded my zsh-quickstart-kit a few weeks back, and my ^R keybinding has been broken ever since.  I finally tracked down the issue, and after much banging of head, it turns out that I didn't have `fzf` installed.  It had been quite awhile since I'd updated zsh-quickstart-kit; the previous version must have been a pre- fzf version.

Maybe the quickstart kit (or the plugin?) should warn that fzf is not installed; or not override the existing bindings, or something?

(`fzf` is pretty cool at first glance, but it was a frustrating few weeks not having search history!)

**Comment by unixorn** [comment]
Excellent point, I'm sorry you had a frustrating experience. I'll add a warning that includes `fzf` install instructions.

**Comment by retnuh** [comment]
Thanks!
