### ISSUE TITLE
Avoid Launching Unnecessary SSHAgents on MacOS

### ISSUE THREAD

**Issue by armarquez** [unixorn/zsh-quickstart-kit#123]
The current version of the `.zshrc` file creates a new `ssh-agent` process whenever the `load-our-ssh-keys()` function is run, which is almost everytime except when on not remote machines.

However, for MacOS platform there is no need to create a new `ssh-agent` as there should be one already running by the OS. So instead of creating news, you can use the one created by the OS. But to keep this code portable for Zshells on Linux and Windows you have to add in some other code for checks.

I fixed this on my `git subtree` version of  this repo by using some code that I snagged from [VS Code docs](https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent):

```bash
if [ -z "$SSH_AUTH_SOCK" ]; then
   # Check for a currently running instance of the agent
   RUNNING_AGENT="`ps -ax | grep 'ssh-agent -s' | grep -v grep | wc -l | tr -d '[:space:]'`"
   if [ "$RUNNING_AGENT" = "0" ]; then
        # Launch a new instance of the agent
        ssh-agent -s &> .ssh/ssh-agent
   fi
   eval `cat .ssh/ssh-agent`
fi
```

Will add a MR with this fix.

**Comment by unixorn** [comment]
Closed in https://github.com/unixorn/zsh-quickstart-kit/pull/124, thanks!
