### ISSUE TITLE
_arguments:comparguments:325: can only be called from completion function

### ISSUE THREAD

**Issue by emjayoh** [unixorn/zsh-quickstart-kit#127]
Not sure why I'm getting this all of a sudden on load.

**Comment by unixorn** [comment]
That's odd. You haven't changed your plugin list lately, I assume?

**Comment by RonanJackson** [comment]
I'm also getting this. It seems to have stemmed from (or what I think) an update to Mac OS to 11.5. It might have also been a brew upgrade though, not sure. Either way, it has also come out of nowhere for me.

**Comment by dglynn** [comment]
I am seeing this error on my Arch Linux install too.

**Comment by unixorn** [comment]
Thanks!

You probably want to switch to [zgenom](https://github.com/jandamm/zgenom) - it's a fork of zgen that's getting actively developed. It's what the kit installs now.
