### ISSUE TITLE
Zgenom OSX plugin is deprecated

### ISSUE THREAD

**Issue by jfmcdowell** [unixorn/zsh-quickstart-kit#152]
Zgenom throws the following error:
-- zgenom: Deleting `/Users/jfmcdowell/.zgenom/init.zsh` ...
The `osx` plugin is deprecated and has been renamed to `macos`.
Please update your .zshrc to use the `macos` plugin instead.

This is because Oh My ZSH [deprecated the plugin.
](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/osx)

**Comment by unixorn** [comment]
Thanks, I'll fix it.

**Comment by jfmcdowell** [comment]
Sorry @unixorn, I was going to submit a PR but got roped into a meeting.

**Comment by unixorn** [comment]
np, it was only a two line change :-)
