### ISSUE TITLE
use can_haz instead of canhaz

### ISSUE THREAD

**Issue by timwisbauer-contsec** [unixorn/zsh-quickstart-kit#156]
[This commit](https://github.com/unixorn/zsh-quickstart-kit/commit/c6e222c6f8297640ba03b1e106c5d565e87e471a) recently introduced support for exa, but may be using `canhaz` instead of `can_haz`.  Whenever I open a new shell `canhaz` creates two files (`exa` and `tree`) in my working directory.

```
❯ which canhaz
canhaz () {
	mkdir -p $(dirname "${1}") && touch "${1}"
}
❯ which can_haz
can_haz () {
	which "$@" > /dev/null 2>&1
}
```

**Comment by unixorn** [comment]
Ugh, thanks for the heads up

**Comment by timwisbauer-contsec** [comment]
Thanks for the quick fix!

**Comment by unixorn** [comment]
np, thanks for the catch.
