### ISSUE TITLE
Add 1password ssh-agent support

### ISSUE THREAD

**Issue by unixorn** [unixorn/zsh-quickstart-kit#179]
1Password 8 beta supports storing ssh keys in your 1Password vault. Add support not starting ssh-agent if 1Password is enabled.

**Describe the solution you'd like**

Detect 1Password ssh and skip `ssh-agent` launch.

**Comment by jfmcdowell** [comment]
[#243](https://github.com/unixorn/zsh-quickstart-kit/pull/243) implements support for the 1Password ssh-agent.

**Comment by unixorn** [comment]
Closed by #243

**Comment by unixorn** [comment]
Thanks for the contribution, @jfmcdowell
