### ISSUE TITLE
Request to include (not an issue)

### ISSUE THREAD

**Issue by ss-o** [unixorn/zsh-quickstart-kit#195]
Hey, :wave: 

> THIS IS NOT AN ISSUE.

Long time no see, :see_no_evil:

I would like live to fetch your docs to mine if you are alright with it.
-> https://github.com/unixorn/zsh-quickstart-kit/edit/main/Readme.md -> https://z.digitalclouds.dev/community/intro

Also would like to invite you to check out [Trunk](https://trunk.io/) which simplifies checking, testing, and merging code, allowing you to focus on writing features instead of babysitting PRs. :octocat: 

> Still beta, but I use it on all repositories with no issues.

- https://app.trunk.io
- https://join.slack.com/t/trunkcommunity/shared_invite/zt-1a8wpv5hv-X8lkqEq6AXr~gIQHsmr7gQ

Sorry for opening a non-issue.

---

P.S: As we spoke about translations here is my summary:

Most visitors (Zsh-related content) are from China and Japan which makes it easy to collaborate on translations. All other languages vary depending on the project-specific community. [1^]

It's very time-consuming to maintain large docs and especially with often changes. A single-page readme should be easy (mostly automated, similar to linters). [2^]

So in a conclusion, if docs are a single page and without often changes is worth translating (price around $0.06 to $0.20 if buying). If still interested I can provide all the required information.

[1^]: https://crowdin.digitalclouds.dev/z-shell/zh-CN
[2^]: https://github.com/z-shell/zw/actions/workflows/crowdin-download.yml

**Comment by unixorn** [comment]
If you want to link the readme into your docs, feel free to do so. I think that'll be easier than a direct copy since you won't have to keep recopying as I update the kit.

As far as translations go, I'm happy to accept contributed translates as `README.$LANGUAGE_CODE`, but I don't get paid for the kit and don't want to pay for translations every time I update things.

Thanks!
