### ISSUE TITLE
Replace highlight plugin

### ISSUE THREAD

**Issue by neiromaster** [unixorn/zsh-quickstart-kit#212]
What do you think about replacing [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) with [fast-syntax-highlighting](https://github.com/zdharma-continuum/fast-syntax-highlighting)?

fast-syntax-highlighting colors commands faster and more correctly

**Comment by unixorn** [comment]
I'll test drive it for a bit, but faster is better, so if I don't run into any issues I'll swap it in.
