### ISSUE TITLE
[BUG] Check to see if monterey is installed is incorrect

### ISSUE THREAD

**Issue by rcrdlbl** [unixorn/zsh-quickstart-kit#226]
on line 286, it checks to see if the version is greater than 21, but my monterey install (12.6) returns "21G115" for the command you're running to check whether or not to run ssh-add --apple-load-keychain.

This causes the function to not load any SSH keys from the ~/.ssh folder other than the ones w/ default filenames.

I'm not totally sure if it's just as simple as changing the "greater than" to a "greater than or equals" or if it's a more involved update.

**Comment by rcrdlbl** [comment]
somewhat related question: is there a recommended way to turn off the default behavior echoing your current ssh keys to the console? it interferes with PL10K's instant prompt and causes it to display a loud warning message every time i open my terminal

**Comment by unixorn** [comment]
I really wish macOS would use integer versions, I'll have to poke at `sw_vers` and see if I can coax a more easily parsed version out of it.

For the second, I'll do an update today that will add `zqs disable|enable ssh-key-listing` commands

**Comment by rcrdlbl** [comment]
seems to work now, thanks!

**Comment by unixorn** [comment]
Thanks for the confirmation
