### ISSUE TITLE
[BUG] Prompt asks to install ssh-askpass on macos ventura

### ISSUE THREAD

**Issue by stevenwu** [unixorn/zsh-quickstart-kit#236]
# Describe the bug

Quickstart `zsh-quickstart-check-for-ssh-askpass` is checking for `ssh-askpass` which isn't installed by default on macos. Older zsh-quickstart-kit versions did not have this issue. 

## To Reproduce

1. Open a terminal on latest version of zsh-quickstart-kit and macos Ventura
2. Prompt shows
```
You'll need to install ssh-askpass for the quickstart to prompt,
for your ssh key/s passphrase on shell startup.
This is the default behavior for ssh-add.
https://www.man7.org/linux/man-pages/man1/ssh-add.1.html#ENVIRONMENT
If you would like the prompt in your shell on startup.
Enable the following zqs setting:
zqs enable-ssh-askpass-require true
```

## Expected behavior

Prompt should load without asking to install `ssh-askpass`.

## Desktop (please complete the following information):

- OS/distro: macOS
- Version: Ventura

**Comment by unixorn** [comment]
Thanks. I'll update it so it only checks for `ssh-askpass` in your `$PATH` if the askpass feature is enabled.

I haven't updated to Ventura on any of my machines yet, thanks for letting me know.
