### ISSUE TITLE
[BUG] command not found: zgenom

### ISSUE THREAD

**Issue by neiromaster** [unixorn/zsh-quickstart-kit#242]
# Describe the bug

When I start the terminal, I get errors in the files inside `.zshrc.pre-plugins.d/`

```
/home/max/.zshrc.pre-plugins.d/001-fzf-tab.zsh:1: command not found: zgenom
/home/max/.zshrc.pre-plugins.d/002-zsh-exa.zsh:1: command not found: zgenom
```

## To Reproduce

1. Create file 001-plugin-name.zsh
2. Add `zgenom load repo/plugin-name && zgenom save`
3. Restarting the terminal

## Expected behavior

Successful launch of plugins

## Desktop (please complete the following information):

- OS/distro: Manjaro
- Version Latest

**Comment by JaseHadd** [comment]
@neiromaster I've experienced this too, I've only just gotten around to fixing it, and pull request #245 was my solution. It supports loading additional plugins by adding them line-by-line to a `~/.zqs-additional-plugins` file.
