### ISSUE TITLE
Zi as framework

### ISSUE THREAD

**Issue by neiromaster** [unixorn/zsh-quickstart-kit#260]
# Feature Request

## Is your feature request related to a problem? Please describe.

Have you tried the Zi framework for zsh (https://wiki.zshell.dev/)? It has a lot of features, such as downloading and using applications from github, as well as Turbo mode.

**Comment by unixorn** [comment]
I'm not going to switch the underlying framework of the kit.

Also, there are issues with zi - see https://recurse.social/@dylnuge/112224580867240812 thread for details
