### ISSUE TITLE
[BUG] SSH-agent is completely broken when 1Password CLI is installed on Linux

### ISSUE THREAD

**Issue by daemonspudguy** [unixorn/zsh-quickstart-kit#265]
# Describe the bug
SSH-agent is completely broken when 1Password CLI is installed on Linux

## To Reproduce

1. Have 1password CLI installed on Linux
2. Open terminal
## Expected behavior

The ssh-agent lists the keys

## Desktop (please complete the following information):

- OS/distro: Ubuntu 
- Version 22.10

## Additional context

The change that broke this is #243

**Comment by daemonspudguy** [comment]
Update: On Linux, 1Password's agent.sock file is in ~/.1password

**Comment by unixorn** [comment]
Thanks for letting me know where the sock file is, that'll make this easier to fix

**Comment by unixorn** [comment]
@daemonspudguy - please try checking out the `fix-1p-on-linux` branch and let me know if that fixes the issue.

**Comment by daemonspudguy** [comment]
That's actually how I ended up fixing it, so it should work.

**Comment by daemonspudguy** [comment]
No, the file is ~/.1password/agent.sock.

**Comment by daemonspudguy** [comment]
~/.1password is a folder.

**Comment by daemonspudguy** [comment]
The path is exactly "~/.1password/agent.sock"
