### ISSUE TITLE
remove `Agent PID 12345`

### ISSUE THREAD

**Issue by aurkaxi** [unixorn/zsh-quickstart-kit#274]
everytime i open terminal i see `agent pid xxxxx`. I don't know what plugin is that, i don't think i have any use of that. i don't want to see this line, neither i want that plugin. 
in ReadMe there is a section to add plugins. i couldn't find anything to remove a plugin. can you help me, please?

**Comment by unixorn** [comment]
Create a `~/.zsh-quickstart-local-plugins` file with only the plugins you want in it. I suggest that you start with a copy of `.zsh-quickstart-local-plugins-example`
