### ISSUE TITLE
[BUG] cannot surpress p10k warning console output

### ISSUE THREAD

**Issue by aurkaxi** [unixorn/zsh-quickstart-kit#275]
# Describe the bug

When a terminal is open powerlevel10k warns that console output during zsh initialization is detected.
## To Reproduce

1. Fresh Install. Open Terminal. Boom Error
2.  in ~/.zshrc it is already written to start quitely.
```zsh
❯ bat ~/.zshrc | grep -i powerlevel9k_instant_prompt
  export POWERLEVEL9K_INSTANT_PROMPT='quiet'
```
So i didn't make any modification here.
3. Readme says to create a fragment file in ~/.zshrc.d/
4. file name: `quite_p10k_warn`. i tried with `.zsh` extention with and without: same result.
```
───────┬────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /home/aurka/.zshrc.d/quite_p10k_warn
───────┼────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ echo "My fragment file is being executed."
   2   │ echo "POWERLEVEL9K_INSTANT_PROMPT is currently set to: $POWERLEVEL9K_INSTANT_PROMPT"
   3   │ typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
───────┴────────────────────────────────────────────────────────────────────────────────────────────────
```
and yes after the big warning message i can see my echo.

## Expected behavior

No warning message from p10k.

## Screenshots

![image](https://github.com/unixorn/zsh-quickstart-kit/assets/72933395/5ef2e0e6-d1cd-48c5-adbe-8a57dbe8ea5f)

## Desktop (please complete the following information):

- OS/distro: ArchLinux
- Version: i don't know what version you are referring to. archlinux is latest. updated today, just before installing quickstart. don't know how to check quickstart version. commit: 619d816

**Comment by unixorn** [comment]
Try setting it in the `.zshrc.pre-plugins.d` - that will set your env var before the plugins/theme are loaded.
