### ISSUE TITLE
[BUG] FZF_PATH variable not pointing to FZF installed with Brew

### ISSUE THREAD

**Issue by saumikn** [unixorn/zsh-quickstart-kit#286]
I followed along with the instructions and installed `fzf` with `brew install fzf`, cloned the main repo into my home directory, and then set up the terminal with `p10k configure`.

However, whenever I make a new shell, I'm getting the following warning: `/Users/saumik/.fzf.zsh:source:13: no such file or directory: /Users/saumik/.fzf/shell/key-bindings.zsh`

Upon further inspection, it seems like `brew` installs `fzf` in `/usr/local/Cellar`, but the `.fzf.zsh` file is looking for `FZF_PATH`, which has somehow been set to `/Users/saumik/.fzf`.

I could manually edit the `.fzf.zsh` file to point to `/usr/local/Cellar`, but I'm not sure why this is happening by default.

Any idea what's going wrong, or if I'm missing a step?

**Comment by unixorn** [comment]
I'll take a look this weekend - I'm kind of swamped at work this week

**Comment by unixorn** [comment]
Thanks, @neiromaster

**Comment by lonr** [comment]
I'm using Linux and installed fzf with a package manager. I got the same error message.
I replaced the related part in `.fzf.zsh` with [`source <(fzf --zsh)`](https://github.com/junegunn/fzf?tab=readme-ov-file#setting-up-shell-integration).
FYI: [release notes about `eval "$(fzf --zsh)"` of fzf 0.48.0](https://github.com/junegunn/fzf/releases/tag/0.48.0)
