### ISSUE TITLE
New starter-kit error

### ISSUE THREAD

**Issue by alo0oz** [unixorn/zsh-quickstart-kit#48]
New starter kit shows these following errors
`-- zgen: Failed to load /home/arafat/.zgen/robbyrussell/oh-my-zsh-master -- oh-my-zsh.sh
`
And
 `It has been 17781 days since your zsh quickstart kit was updated
Checking for zsh-quickstart-kit updates...
~/.zsh-quickstart-kit-master/zsh ~
fatal: not a git repository (or any of the parent directories): .git
No quickstart marker found, is your quickstart a valid git checkout?
`

**Comment by unixorn** [comment]
Closed for inactivity.
