### ISSUE TITLE
Conditional PATH in /etc/paths.d didn't be loaded in macOS

### ISSUE THREAD

**Issue by niheaven** [unixorn/zsh-quickstart-kit#56]
Several softwares put there PATH in /etc/paths.d folder (e.g. TeXLive, dotnet, XQuartz), and zsh-quickstart-kit doesn't handle them. This seems to be a bug.

**Comment by unixorn** [comment]
You're right, the quick start is replacing the `$PATH` passed to ZSH by the OS, that's a bug.
