### ISSUE TITLE
Stuck on zgen setup part of readme

### ISSUE THREAD

**Issue by BrianGilbert** [unixorn/zsh-quickstart-kit#6]
It's not clear to me, when reading the readme on github, that you are supposed to download the quickstart repo, or where would be a good location to download it to.

I read step 2 as referring to the repo downloaded in step 1, but I think it's referring to downloaded version of the quickstart repo..?

Do you have a suggested location to download the quickstart repo?

**Comment by unixorn** [comment]
It doesn't really matter where you download it since you'll use GNU stow to symlink the zsh dotfiles from it to your `~`. I'll update the readme to clarify the installation.

Thanks for the feedback, it helps me make the kit more useful.
