### ISSUE TITLE
[Suggestion] Disable OMZ's built-in auto-update

### ISSUE THREAD

**Issue by mingaldrichgan** [unixorn/zsh-quickstart-kit#62]
Since **zsh-quickstart-kit** includes **autoupdate-zgen** by default, would you consider adding `DISABLE_AUTO_UPDATE=true` to the included `.zshrc` to avoid getting prompted by Oh-My-Zsh to update itself? (Obviously, we can add it to our own custom configurations but it seems like a reasonable inclusion in the default config.) Thanks for your consideration!

**Comment by unixorn** [comment]
I'm hesitant to make changes that will alter behavior for existing users. I'm willing to make it a toggle that defaults to the current  behavior, though.

**Comment by unixorn** [comment]
on further thought, better for it to happen when the other plugins are being updated instead of on OMZ's schedule.
