### ISSUE TITLE
Stow throws Warning! about targest

### ISSUE THREAD

**Issue by jefheaton** [unixorn/zsh-quickstart-kit#7]
Ran through instructions per the readme and got this error when running the `stow --target=/Users/YourUsername zsh` in the top level of the repo

```
WARNING! stowing zsh would cause conflicts:
  * existing target is neither a link nor a directory: .zshrc
All operations aborted.
```

**Comment by jefheaton** [comment]
Figured it out. I needed to close my ~ so Finder wouldn't create a DS_Store, delete the existing one, and remove my old .zshrc (hard to do if you're already using zsh).

Might be worth a mention in the Readme.

**Comment by newpublicvoid** [comment]
thanks ! @jefheaton
