### ISSUE TITLE
n00b question about zgen vs oh-my-zsh

### ISSUE THREAD

**Issue by haakonstorm** [unixorn/zsh-quickstart-kit#71]
Why does this setup load oh-my-zsh when it already is using zgen? 
Cannot zgen alone + straight zsh config provide the same functionality?
I'm asking because people write ohmy is slow. I've read zgen is good, and thats how I found this repo. Is it not an issue anymore?

**Comment by unixorn** [comment]
So you can use oh-my-zsh builtin plugins without using oh-my-zsh's slow loader.

**Comment by BrianGilbert** [comment]
@unixorn how do we do that?
