### ISSUE TITLE
Removing SSH key echo in .zshrc

### ISSUE THREAD

**Issue by emjayoh** [unixorn/zsh-quickstart-kit#75]
I could be missing something but is there a way to do this without modifying `.zshrc` directly (would rather not)?

I don't currently see anything in source or docs.

**Comment by KlausDevWalker** [comment]
Following here for the same reason.

**Comment by unixorn** [comment]
I'll make a change to not echo it in `.zshrc` and instead make it an example that can be dropped into `~/.zshrc.d/something`

**Comment by unixorn** [comment]
To prevent behavior change for existing users, I've updated it to not display the key list if `DONT_PRINT_SSH_KEY_LIST` is set, and moved the display after files are loaded from `~/.zshrc.d`.

**Comment by KlausDevWalker** [comment]
It worked like a charm, @unixorn! Thank you very much! :clap::clap::clap:

**Comment by emjayoh** [comment]
Thanks for this. This might just be me being rusty on my ricing, but I now see a key added message _only_ on initial startup. The constant defined does not alter this. I set up my machine recently and don't seem to recall this happening.
