### ISSUE TITLE
Default zgen directory to hidden

### ISSUE THREAD

**Issue by darrist** [unixorn/zsh-quickstart-kit#76]
Hi, thanks for the awesome zsh kit. No doubt this is the best kit around.

I'd like to make a suggestion to use `/.zgen` instead of `zgen`, because no point seeing a boilerplate zgen directory for most users.

**Comment by unixorn** [comment]
zgen already uses `~/.zgen` to store local checkouts of plugins.

**Comment by darrist** [comment]
I have this line that git clone into `~/zgen` from the repo scripts. Am I doing something wrong?

**Comment by unixorn** [comment]
that does the clone of the zgen framework. Then the framework checks out all the plugins/themes into `~/.zgen`.

Agreed, it's a bit confusing. You could clone into `~/.zgen-framework` if you want to keep your home directory tidy.
