### ISSUE TITLE
Default plugin is causing duplicate characters

### ISSUE THREAD

**Issue by darrist** [unixorn/zsh-quickstart-kit#77]
![image](https://user-images.githubusercontent.com/21124691/82206270-85ca4500-993a-11ea-8c64-857ab1f6e925.png)

Like above image, I am not too sure which default plugin is causing character to jump.

**Comment by unixorn** [comment]
Sorry it tok so long to respond - I haven't had any other reports of this, did you eventually track it down?

**Comment by darrist** [comment]
It's terminal configuration issue, not related to the shell.
