### ISSUE TITLE
Assistance with font's instructions. 

### ISSUE THREAD

**Issue by DanitiKain** [unixorn/zsh-quickstart-kit#86]
Install the patched font in a valid X font path. Valid font paths can be listed with xset q: mv YourChosenPowerlineFont.otf ~/.fonts
Update the font cache for the path the font was installed in (root privileges may be needed for updating the font cache for some paths): fc-cache -vf ~/.fonts/

Can you assist a little more in these instructions. I have installed powerline and nerdfonts. I searched using catfish and only found this one file. PowerlineSymbols.otf in /usr/share/fonts/OTF/

I cannot find anything labled with powerline and file type of otf besides that. 

In the past with Arch and installing Oh-My-Zsh I don't recall having to mv powerline fonts to my local fonts. Maybe these instructions do not apply to Arch.

**Comment by unixorn** [comment]
I don't use linux as a desktop, just as headless servers. I got the font setup instructions from a coworker at a previous job.

If you do find a solution on Arch, please PR it.
