### ISSUE TITLE
Git Clone Issue

### ISSUE THREAD

**Issue by DanitiKain** [unixorn/zsh-quickstart-kit#87]
git clone git@github.com:unixorn/zsh-quickstart-kit.git
Cloning into 'zsh-quickstart-kit'...
The authenticity of host 'github.com (140.82.113.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.113.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by unixorn** [comment]
That is an issue with your local git setup, not the repository.

**Comment by DanitiKain** [comment]
https://gist.github.com/adamjohnson/5682757

Resolution is here.
