### ISSUE TITLE
Local Files Overwritten by merge

### ISSUE THREAD

**Issue by DanitiKain** [unixorn/zsh-quickstart-kit#94]
How do I resolve this issue...

From https://github.com/unixorn/zsh-quickstart-kit
   0c5bad9..2064c6b  master           -> origin/master
 + 755f689...e3f8677 switch-to-zgenom -> origin/switch-to-zgenom  (forced update)
Updating 0c5bad9..2064c6b
error: Your local changes to the following files would be overwritten by merge:
	zsh/.zshrc
Please commit your changes or stash them before you merge.
Aborting

**Comment by DanitiKain** [comment]
Any help on this one?

**Comment by unixorn** [comment]
The kit was designed to load files in `~/.zshrc.d` so that you don't have to maintain a fork if you want to customize `.zshrc`. Put your local changes into files in `~/.zshrc.d` and they'll get sourced by the default `.zshrc`

**Comment by DanitiKain** [comment]
Ok I moved my custom .zshrc to .zshrc.d named .mycustomzshrc and then refetched the git hub. Hopeful that is the correct course of action if not please let me know.
