### ISSUE TITLE
Walk through setup/quickstart again to change settings (or toggle them after initially setting up)

### ISSUE THREAD

**Issue by wsloth** [unixorn/zsh-quickstart-kit#95]
Hey,

I started using this quickstart kit to quickly setup ZSH with loads of features, and I absolutely love it!
One thing I did misconfigure though was to have the more compact terminal view:

![image](https://user-images.githubusercontent.com/4933907/101926709-d6093d00-3bd3-11eb-8eb0-935d93481af4.png)

I want to change it back to show the full powerline visual instead of compacting the log of commands previously executed, but I am unsure where to look or where to toggle individual settings.

Is there a way to run the initial setup again, or toggle individual choices that were made during the initial setup?

**Comment by unixorn** [comment]
The theme included in the quickstart is powerlevel10k. You can re-run the configurator by running `p10k configure`.

I'll update the readme accordingly, thanks

**Comment by wsloth** [comment]
Thanks, it really was that easy 😄 I didn't know in which of the plugins to look for this change, but this makes sense. Works like a charm! ✌️
